// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/andrejkoleshko/VSRPP-LAB/lab8/internal/pkg/app/cli (interfaces: WeatherInfo)

// Package mock_cli is a generated GoMock package.
package mock_cli

import (
	reflect "reflect"

	models "github.com/andrejkoleshko/VSRPP-LAB/lab8/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockWeatherInfo is a mock of WeatherInfo interface.
type MockWeatherInfo struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherInfoMockRecorder
}

// MockWeatherInfoMockRecorder is the mock recorder for MockWeatherInfo.
type MockWeatherInfoMockRecorder struct {
	mock *MockWeatherInfo
}

// NewMockWeatherInfo creates a new mock instance.
func NewMockWeatherInfo(ctrl *gomock.Controller) *MockWeatherInfo {
	mock := &MockWeatherInfo{ctrl: ctrl}
	mock.recorder = &MockWeatherInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherInfo) EXPECT() *MockWeatherInfoMockRecorder {
	return m.recorder
}

// GetTemperature mocks base method.
func (m *MockWeatherInfo) GetTemperature(arg0, arg1 float64) models.TempInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemperature", arg0, arg1)
	ret0, _ := ret[0].(models.TempInfo)
	return ret0
}

// GetTemperature indicates an expected call of GetTemperature.
func (mr *MockWeatherInfoMockRecorder) GetTemperature(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemperature", reflect.TypeOf((*MockWeatherInfo)(nil).GetTemperature), arg0, arg1)
}
